### ISSUE TITLE
sqloj可以参考算法OJ系统

### ISSUE THREAD

**Issue by HugeMing** [PTYin/SQLOJ#4]
可以在基础上增加OJ系统的一些功能，比如问题，比赛，排名，状态，后天可以查看所有学生等等，不知道是否还会继续更新

**Comment by ptyin** [comment]
谢谢支持！之后会持续更新，目前的计划是先完善和优化最核心的判题部分；之后优先实现查看/管理所有学生的功能；比赛和排名之后会考虑更新。

**Comment by HugeMing** [comment]
好的，期待，后续完善了用于教学使用，这种SQL的OJ实在是少之又少啊，有没有用户交流群大家可以一起交流一下呀




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PTYin/sqloj"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月16日(星期二) 晚上11:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PTYin/sqloj] sqloj可以参考算法OJ系统 (Issue #4)





 
谢谢支持！之后会持续更新，目前的计划是先完善和优化最核心的判题部分；之后优先实现查看/管理所有学生的功能；比赛和排名之后会考虑更新。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
