### ISSUE TITLE
docker build 报错

### ISSUE THREAD

**Issue by Galio1020** [PTYin/SQLOJ#5]
HTTP error 404 while getting https://mirrors.bfsu.edu.cn/pypi/web/packages/67/b8/0322016b9ce09a64fba9018211e7c35fd51380527ffd9ea248744f389239/Flask_PyMongo-2.3.0-py2.py3-none-any.whl#sha256=8a9577a2c6d00b49f21cb5a5a8d72561730364a2d745551a85349ab02f86fc73 (from https://mirrors.bfsu.edu.cn/pypi/web/simple/flask-pymongo/)
  Could not install requirement Flask-PyMongo from https://mirrors.bfsu.edu.cn/pypi/web/packages/67/b8/0322016b9ce09a64fba9018211e7c35fd51380527ffd9ea248744f389239/Flask_PyMongo-2.3.0-py2.py3-none-any.whl#sha256=8a9577a2c6d00b49f21cb5a5a8d72561730364a2d745551a85349ab02f86fc73 (from -r /opt/sqloj/requirements.txt (line 5)) because of error 404 Client Error: Not Found for url: https://mirrors.bfsu.edu.cn/pypi/web/packages/67/b8/0322016b9ce09a64fba9018211e7c35fd51380527ffd9ea248744f389239/Flask_PyMongo-2.3.0-py2.py3-none-any.whl
Could not install requirement Flask-PyMongo from https://mirrors.bfsu.edu.cn/pypi/web/packages/67/b8/0322016b9ce09a64fba9018211e7c35fd51380527ffd9ea248744f389239/Flask_PyMongo-2.3.0-py2.py3-none-any.whl#sha256=8a9577a2c6d00b49f21cb5a5a8d72561730364a2d745551a85349ab02f86fc73 (from -r /opt/sqloj/requirements.txt (line 5)) because of HTTP error 404 Client Error: Not Found for url: https://mirrors.bfsu.edu.cn/pypi/web/packages/67/b8/0322016b9ce09a64fba9018211e7c35fd51380527ffd9ea248744f389239/Flask_PyMongo-2.3.0-py2.py3-none-any.whl for URL https://mirrors.bfsu.edu.cn/pypi/web/packages/67/b8/0322016b9ce09a64fba9018211e7c35fd51380527ffd9ea248744f389239/Flask_PyMongo-2.3.0-py2.py3-none-any.whl#sha256=8a9577a2c6d00b49f21cb5a5a8d72561730364a2d745551a85349ab02f86fc73 (from https://mirrors.bfsu.edu.cn/pypi/web/simple/flask-pymongo/)
好像是镜像站上的镜像已被删除或改变

**Comment by ptyin** [comment]
感谢告知，之前为了构建方便用了镜像源，已经在新版本中去掉了。其次PyMongo更改了较多api，当前版本运行会出现功能错误。最近我正在用spring重构项目，目前还没有完成，如果有兴趣可以切换到spring-app分支查看。

**Comment by ptyin** [comment]
如果构建没有问题的话我就close issue了哈

**Comment by Galio1020** [comment]
> 如果构建没有问题的话我就close issue了哈
没问题了，谢谢
